name: domain
publish_to: none
description: "Un nuevo proyecto de paquete Flutter para manejar la lógica de dominio."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../../packages/data
  flutter_bloc: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0

# La siguiente sección es específica para paquetes Flutter.
flutter:

  # Para agregar assets a tu paquete, agrega una sección de assets, como esta:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # Para detalles sobre assets en paquetes, ver
  # https://flutter.dev/to/asset-from-package
  #
  # Un asset de imagen puede referirse a una o más "variantes" específicas de resolución, ver
  # https://flutter.dev/to/resolution-aware-images

  # Para agregar fuentes personalizadas a tu paquete, agrega una sección de fuentes aquí,
  # en esta sección "flutter". Cada entrada en esta lista debe tener una
  # clave "family" con el nombre de la familia de fuentes, y una clave "fonts" con una
  # lista que da el asset y otros descriptores para la fuente. Por ejemplo:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # Para detalles sobre fuentes en paquetes, ver
  # https://flutter.dev/to/font-from-package
